-- USING CROSS APPLY TO RETRIEVE RECORDS ONLY WHEN THERE IS MATCHING VALUE BETWEEN LEFT AND RIGHT
-- THIS COULD BE DONE WITH INNER JOIN AS WELL, BUT HERE WE ARE USING CROSS APPLY
-- DISPLAY THE INFORMATION FROM ORDERS AND DETAIL ORDERS USING CROSS APPLY

SELECT H.PurchaseOrderNumber, H.OrderDate,
D.ProductID, D.OrderQty,  D.UnitPrice
FROM Sales.SalesOrderHeader AS H

CROSS APPLY 
( SELECT D.ProductID, D.OrderQty,  D.UnitPrice
	FROM SALES.SalesOrderDetail AS D
	WHERE D.SalesOrderID = H.SalesOrderID
	AND H.OrderDate > '06/01/2014'
) AS D

/*
PLEASE NOTE THAT THIS CAN BE DONE WITH INNER JOIN, AND ACTUALLY INNER JOIN WILL BE
BETTER FOR HUMAN READING AND IS LESS CODE.
THERE IS NO SET RULE WHEN TO USE ONE OR THE OTHER, BUT JOIN TEND TO PROCESS SLOWLY WHEN THERE IS MILLIONS OF RECORDS.
TEST BOTH SCENRAIOS IN A REAL WORLD SCENARIO BEFORE MAKE A DECISION.
*/



/*
USING A FUNCTION IN COMBINATION WITH CROSS APPLY

TOPIC: RETURN PRODUCTS IN THE INVENTORY OF ADVENTUREWORKS
CREATE A FUNCTION THAT RETURN THE INVENTORY COUNT FOR A PRODUCT THAT RETURNS A TABLE, THIS IS
TO BE USE IN A CROSS JOIN
*/
CREATE FUNCTION fn_Inventory_Count_For_Product(@ProductID INT)
RETURNS TABLE
AS
RETURN
(
	SELECT PRODUCTID, LOCATIONID, QUANTITY 
	FROM PRODUCTION.ProductInventory 
	WHERE PRODUCTID = @ProductID
)
GO

select * from fn_Inventory_Count_For_Product(1)


/*
NOW, LETS USE CROSS JOIN TO GET THE INFORMATION FOR
ALL PRODUCTS USING THE FUNCTION, AND GET ALL THE PRODUCTS THAT ARE INVENTORIED
*/

SELECT P.Name, P.ProductID, I.QUANTITY, I.LOCATIONID
FROM Production.Product P
CROSS APPLY
	fn_Inventory_Count_For_Product(P.ProductID) AS I
	--WHERE I.Quantity IS NULL  --SHOULD BE ZERO
	--WHERE I.Quantity IS NOT NULL --SHOULD BE THE SAME AMOUNT OF PRODUCTS

/*
ONLY MATCHING VALUES IN BOTH SIDES THE PRODUCT TABLE AND THE FUNCTION WILL BE DISPLAYED

HOW CAN WE BE SURE THAT THERE ARE PRODUCTS THAT ARE NOT INVENTORIED IN THIS QUERY?,
UNCOMMENT THE NULL AND IT SHOULD BE ZERO, BECAUSE THE FUNCTION IS NOT RETURNING PRODUCTS WITH NULL QUANTITY
SO I AM LOOKING PRODUCTS THAT ARE INVENTORIED. IF THERE ARE PRODUCT WITH NO INVENTORY, THEN DO NOT RETURN THE RECORD

*/



/*
USING OUTER APPLY TO RETRIEVE RECORDS  WHEN THERE IS, OR NOT, MATCHING VALUES BETWEEN LEFT AND RIGHT

*/

SELECT P.Name, P.ProductID, I.QUANTITY, I.LOCATIONID
FROM Production.Product P
OUTER APPLY --THIS WILL RETURN ALL RECORDS FROM BOTH SIZES, MATCHING OR NOT
	fn_Inventory_Count_For_Product(P.ProductID) AS I
	--WHERE I.Quantity IS NULL --THIS WILL FIND PRODUCTS WITH NO INVENTORIED
	WHERE I.Quantity IS NOT NULL  -- THIS WILL FIND PRODUCTS THAT ARE ONLY IN THE INVENTORY
	

/*


*/
